### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by evianzhow** [EvianZhow/surge2clash#2]
- [x] Support passing using Base64 URI param
- [x]  Better code separation
- [x] Added test cases for parsing different format `Proxy` sources according to https://github.com/Dreamacro/clash
- [x] `General` section customization support
- [x] Better API documentation
- [x] ~YAML emoji export support~
